# goal
bool[] jars # Selection of Jars
---
# result
int32[] capacities
bool success
string message
---
# feedback
int32[] capacities # How much water is in each jar
int32 eta # Estimated time to complete the action